//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonationManagementEntities : DbContext
    {
        public DonationManagementEntities()
            : base("name=DonationManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAddress> tblAddresses { get; set; }
        public DbSet<tblAddressType> tblAddressTypes { get; set; }
        public DbSet<tblBatch> tblBatches { get; set; }
        public DbSet<tblContactInfo> tblContactInfos { get; set; }
        public DbSet<tblContactInfoType> tblContactInfoTypes { get; set; }
        public DbSet<tblContributionCategory> tblContributionCategories { get; set; }
        public DbSet<tblContribution> tblContributions { get; set; }
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblDonorAdress> tblDonorAdresses { get; set; }
        public DbSet<tblDonorContactInfo> tblDonorContactInfos { get; set; }
        public DbSet<tblDonorGroup> tblDonorGroups { get; set; }
        public DbSet<tblDonorGroupType> tblDonorGroupTypes { get; set; }
        public DbSet<tblDonor> tblDonors { get; set; }
        public DbSet<tblDonorStatus> tblDonorStatuses { get; set; }
        public DbSet<tblDonorType> tblDonorTypes { get; set; }
        public DbSet<tblGender> tblGenders { get; set; }
        public DbSet<tblHouseholdMember> tblHouseholdMembers { get; set; }
        public DbSet<tblHousehold> tblHouseholds { get; set; }
        public DbSet<tblMaritalStatus> tblMaritalStatuses { get; set; }
        public DbSet<tblOrganizationAddress> tblOrganizationAddresses { get; set; }
        public DbSet<tblOrganizationContactInfo> tblOrganizationContactInfos { get; set; }
        public DbSet<tblOrganization> tblOrganizations { get; set; }
        public DbSet<tblPaymentType> tblPaymentTypes { get; set; }
        public DbSet<tblPledgeCampaign> tblPledgeCampaigns { get; set; }
        public DbSet<tblPledge> tblPledges { get; set; }
        public DbSet<tblStateProvince> tblStateProvinces { get; set; }
    }
}
