//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public tblAddress()
        {
            this.tblDonorAdresses = new HashSet<tblDonorAdress>();
            this.tblHouseholds = new HashSet<tblHousehold>();
            this.tblOrganizationAddresses = new HashSet<tblOrganizationAddress>();
        }
    
        public int AddressId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual tblStateProvince tblStateProvince { get; set; }
        public virtual ICollection<tblDonorAdress> tblDonorAdresses { get; set; }
        public virtual ICollection<tblHousehold> tblHouseholds { get; set; }
        public virtual ICollection<tblOrganizationAddress> tblOrganizationAddresses { get; set; }
    }
}
