//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContributionCategory
    {
        public tblContributionCategory()
        {
            this.tblContributions = new HashSet<tblContribution>();
            this.tblPledgeCampaigns = new HashSet<tblPledgeCampaign>();
        }
    
        public int ContributionCategoryId { get; set; }
        public string ContributionCategory { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual ICollection<tblContribution> tblContributions { get; set; }
        public virtual ICollection<tblPledgeCampaign> tblPledgeCampaigns { get; set; }
    }
}
