//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactInfoType
    {
        public tblContactInfoType()
        {
            this.tblDonorContactInfos = new HashSet<tblDonorContactInfo>();
            this.tblOrganizationContactInfos = new HashSet<tblOrganizationContactInfo>();
        }
    
        public short ContactInfoTypeId { get; set; }
        public string ContactInfoType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<tblDonorContactInfo> tblDonorContactInfos { get; set; }
        public virtual ICollection<tblOrganizationContactInfo> tblOrganizationContactInfos { get; set; }
    }
}
