//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContribution
    {
        public int ContributionId { get; set; }
        public System.DateTime ContributionDate { get; set; }
        public decimal Contribution { get; set; }
        public string Note { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblContributionCategory tblContributionCategory { get; set; }
        public virtual tblDonor tblDonor { get; set; }
        public virtual tblPaymentType tblPaymentType { get; set; }
    }
}
