//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonor
    {
        public tblDonor()
        {
            this.tblContributions = new HashSet<tblContribution>();
            this.tblDonorAdresses = new HashSet<tblDonorAdress>();
            this.tblDonorContactInfos = new HashSet<tblDonorContactInfo>();
            this.tblDonorGroups = new HashSet<tblDonorGroup>();
            this.tblHouseholdMembers = new HashSet<tblHouseholdMember>();
            this.tblPledges = new HashSet<tblPledge>();
        }
    
        public int DonorId { get; set; }
        public string Description { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<tblContribution> tblContributions { get; set; }
        public virtual ICollection<tblDonorAdress> tblDonorAdresses { get; set; }
        public virtual ICollection<tblDonorContactInfo> tblDonorContactInfos { get; set; }
        public virtual ICollection<tblDonorGroup> tblDonorGroups { get; set; }
        public virtual tblDonorType tblDonorType { get; set; }
        public virtual tblMaritalStatus tblMaritalStatus { get; set; }
        public virtual tblOrganization tblOrganization { get; set; }
        public virtual ICollection<tblHouseholdMember> tblHouseholdMembers { get; set; }
        public virtual ICollection<tblPledge> tblPledges { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblDonorStatus tblDonorStatus { get; set; }
    }
}
