//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonorGroupType
    {
        public tblDonorGroupType()
        {
            this.tblDonorGroups = new HashSet<tblDonorGroup>();
        }
    
        public short DonorGroupTypeId { get; set; }
        public string DonorGroupType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<tblDonorGroup> tblDonorGroups { get; set; }
    }
}
