//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonorGroup
    {
        public int DonorGroupId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual tblDonorGroupType tblDonorGroupType { get; set; }
        public virtual tblDonor tblDonor { get; set; }
    }
}
