//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPledgeCampaign
    {
        public tblPledgeCampaign()
        {
            this.tblPledges = new HashSet<tblPledge>();
        }
    
        public int PledgeCampaignId { get; set; }
        public string PledgeCampaignName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TargetAmount { get; set; }
        public bool IsActive { get; set; }
        public bool HasCompleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual tblContributionCategory tblContributionCategory { get; set; }
        public virtual ICollection<tblPledge> tblPledges { get; set; }
    }
}
