//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateProvince
    {
        public tblStateProvince()
        {
            this.tblAddresses = new HashSet<tblAddress>();
        }
    
        public int StateProvinceId { get; set; }
        public string StateProvinceName { get; set; }
        public string StateProvicenCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual ICollection<tblAddress> tblAddresses { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
